// Test1/Jenkinsfile 파일 내용
pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                    cd Test1/  // <--- 이 줄을 추가하여 Test1 디렉토리로 이동
                    make
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd Test1/  // <--- 테스트도 Test1 디렉토리에서 실행해야 한다면
                    make check
                '''
                junit 'Test1/test-reports/**/*.xml' // <--- 보고서 경로도 Test1 기준
            }
        }
        stage('Deploy') {
            steps {
                sh 'make publish' // 이 부분도 cd 필요할 수 있음
            }
        }
    }
}